# Generated by Django 6.0.3 on 2026-03-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talvo1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=140)),
                ('target_company', models.CharField(max_length=140)),
                ('difficulty', models.CharField(default='Medium', max_length=20)),
                ('interview_type', models.CharField(default='Behavioral', max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_index', models.PositiveIntegerField()),
                ('user_transcript', models.TextField(blank=True)),
                ('ai_response', models.TextField()),
                ('ai_feedback', models.TextField(blank=True)),
                ('user_audio_path', models.CharField(blank=True, max_length=255)),
                ('ai_audio_path', models.CharField(blank=True, max_length=255)),
                ('processing_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='talvo1.interviewsession')),
            ],
            options={
                'ordering': ['turn_index', 'id'],
                'unique_together': {('session', 'turn_index')},
            },
        ),
    ]
